# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [118]:
# Please consult the lectures
#A vector is a one-dimensional array (like a list), while a matrix is a two-dimensional array (like a table with rows and columns).

**2. How to import `NumPy` library?** 

In [120]:
# To avoid overwriting the output, please code here 
import numpy as np


**3. Convert the given Python list into NumPy array and check its data type**

In [122]:
list_1 = [1,2,3,4,5]

In [123]:
# To avoid overwriting the output, please code here 
list_1 = [1, 2, 3, 4, 5]
array_1 = np.array(list_1)
data_type = type(array_1)
(array_1, data_type)



(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [125]:
# To avoid overwriting the output, please code here 
array_2 = np.arange(6)



**5. Generate an `array of "5" zeros` **

In [127]:
# To avoid overwriting the output, please code here 
zeros_array = np.zeros(5)



**6. Generate the following `matrix`.**

In [129]:
# To avoid overwriting the output, please code here 
matrix_zeros = np.zeros((3, 4))



**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [131]:
# To avoid overwriting the output, please code here 
ones_array = np.ones(5)

**8. Generate an array of "5" tens.**

In [133]:
# To avoid overwriting the output, please code here 
tens_array = np.ones(5) * 10

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [135]:
# To avoid overwriting the output, please code here 
even_array = np.arange(52, 100, 2)


**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [137]:
# To avoid overwriting the output, please code here 
linear_array, step = np.linspace(0, 1, 10, retstep=True)
(linear_array, step)


(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [139]:
# To avoid overwriting the output, please code here 
vector = np.arange(25)



In [140]:
# Generating vector array

In [141]:
# To avoid overwriting the output, please code here 

In [142]:
# reshape to convert into 2-d
matrix_2d = vector.reshape(5, 5)

In [143]:
# To avoid overwriting the output, please code here 

In [144]:
# Using shape

**12. Please generate the following matrix.**

In [146]:
# To avoid overwriting the output, please code here 
matrix_custom = np.arange(0.1, 2.6, 0.1).reshape(5, 5)


**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [148]:
# To avoid overwriting the output, please code here 
linspace_matrix = np.linspace(0, 24, 25).reshape(5, 5)
print(linspace_matrix)


[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


**14. What is the main difference between `linspace()` and `arange()`?**

In [150]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

#arange() requires a step size, whereas linspace() needs the number of points.

**15. How to generate a single random integer number using NumPy built-in function?**

In [152]:
# To avoid overwriting the output, please code here 

random_integer = np.random.randint(1, 100)


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [154]:
# To avoid overwriting the output, please code here 

rand_matrix = np.random.rand(7, 5)
print(rand_matrix)

[[0.45584712 0.43578934 0.91062095 0.41215981 0.8075516 ]
 [0.48499191 0.90243813 0.73644572 0.24061151 0.35546181]
 [0.15013443 0.83299393 0.14723513 0.32441584 0.5836914 ]
 [0.37403301 0.30319198 0.62420446 0.40124356 0.36100212]
 [0.17250169 0.7649154  0.56841967 0.36537293 0.67919821]
 [0.07224364 0.49121091 0.26265548 0.180695   0.28348023]
 [0.38670087 0.21040594 0.16076504 0.8107021  0.86290675]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [156]:
# To avoid overwriting the output, please code here 

identity_matrix = np.eye(5) * 5


### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 